-- Matikan RLS semua tabel

ALTER TABLE suppliers DISABLE ROW LEVEL SECURITY;
ALTER TABLE materials DISABLE ROW LEVEL SECURITY;
ALTER TABLE outlets DISABLE ROW LEVEL SECURITY;
ALTER TABLE order_sessions DISABLE ROW LEVEL SECURITY;
ALTER TABLE order_request_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE purchase_orders DISABLE ROW LEVEL SECURITY;
ALTER TABLE purchase_order_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE app_settings DISABLE ROW LEVEL SECURITY;
ALTER TABLE roti_branch_mapping DISABLE ROW LEVEL SECURITY;
ALTER TABLE roti_min_stock DISABLE ROW LEVEL SECURITY;
